import {
  BAG_ROUND_COUNTS,
  BAG_ROUND_SECONDS,
  SHADOW_COOL_NAME,
  SHADOW_EMPTY_NAME,
  SHADOW_WEIGHTED_NAME,
  bagFocusFor,
  formatBagRoundNotes,
  type BagWeekday,
} from "@/lib/bag-sessions";
import {
  FRIDAY_GPP_DAY_NUMBER,
  THU_STRENGTH_DAY_NUMBER,
  FRIDAY_GPP_NAMES,
  daruSeedRow,
} from "@/lib/daru-exercises";
import { formVideoFieldsFor } from "@/lib/form-videos";
import {
  MESO_BLOCKS,
  STRENGTH_DAY_BY_BLOCK,
  mesoBlockLabel,
  type MesoBlock,
} from "@/lib/mesocycle";
import { effortLoadText } from "@/lib/rir";

const BAG_OR_SHADOW =
  "Heavy bag or pads if you have them. Bodyweight only: shadow the same work at technical speed — no full power.";

const BAG_WEEKDAYS: BagWeekday[] = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

function daruProgramExercise(name: string, sortOrder: number) {
  return {
    ...daruSeedRow(name, sortOrder),
    ...formVideoFieldsFor(name),
  };
}

function bagRoundBlock(input: { name: string; notes: string; sortOrder: number }) {
  const seconds = BAG_ROUND_SECONDS.intermediate;
  const rounds = BAG_ROUND_COUNTS.intermediate;
  return {
    sortOrder: input.sortOrder,
    name: input.name,
    sets: rounds,
    reps: `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`,
    loadText: "Round clock — fight pace you can repeat",
    restSeconds: 60,
    notes: `${input.notes} ${BAG_OR_SHADOW}`,
    ...formVideoFieldsFor(input.name),
  };
}

function effort(rir: string, note: string, percent?: string) {
  return effortLoadText(rir, note, percent);
}

function liftExercise(input: {
  sortOrder: number;
  name: string;
  sets: number;
  reps: string;
  loadText: string;
  restSeconds: number;
  notes: string;
}) {
  return {
    ...input,
    ...formVideoFieldsFor(input.name),
  };
}

function shadowRounds(emptyNotes: string, weightedNotes: string) {
  return [
    {
      sortOrder: 1,
      name: SHADOW_EMPTY_NAME,
      sets: 1,
      reps: "3:00",
      loadText: "Empty hands — technical pace",
      restSeconds: 30,
      notes: emptyNotes,
      ...formVideoFieldsFor(SHADOW_EMPTY_NAME),
    },
    {
      sortOrder: 2,
      name: SHADOW_WEIGHTED_NAME,
      sets: 1,
      reps: "3:00",
      loadText: "1–3 lb hand weights",
      restSeconds: 45,
      notes: `${weightedNotes} Log seconds and lbs.`,
      ...formVideoFieldsFor(SHADOW_WEIGHTED_NAME),
    },
  ];
}

type SeedExercise = ReturnType<typeof liftExercise>;

function strengthDay(input: {
  dayNumber: number;
  title: string;
  focus: string;
  exercises: SeedExercise[];
}) {
  return {
    dayNumber: input.dayNumber,
    title: input.title,
    focus: input.focus,
    exercises: { create: input.exercises },
  };
}

/** Strength / bike / GPP catalog days for demo-strength-base. One menu per block. */
export function demoStrengthDays() {
  const a = STRENGTH_DAY_BY_BLOCK.A;
  const b = STRENGTH_DAY_BY_BLOCK.B;
  const c = STRENGTH_DAY_BY_BLOCK.C;
  return [
    strengthDay({
      dayNumber: a.monday,
      title: "Day 1 — Lower body strength",
      focus: `Squat, hinge, and anti-rotation · ${mesoBlockLabel("A")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Squat jump or box step-up",
          sets: 4,
          reps: "5",
          loadText: effort("3-5", "Crisp landings. Leave speed in the tank."),
          restSeconds: 45,
          notes: "Explosive primer. Quiet landing. Stop if the knees cave.",
        }),
        daruProgramExercise("Trap-bar deadlift", 2),
        liftExercise({
          sortOrder: 3,
          name: "Goblet squat",
          sets: 4,
          reps: "6",
          loadText: effort("0-2", "Own the bottom.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Hold a dumbbell or kettlebell at your chest. Add lbs when 0-2 RIR is still clean.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Romanian deadlift",
          sets: 3,
          reps: "6",
          loadText: effort("1-3", "Flat back, hamstrings on every rep."),
          restSeconds: 90,
          notes: "Secondary hinge. Soft knees. This is not a second max pull after the trap bar.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Reverse lunge",
          sets: 3,
          reps: "8 / leg",
          loadText: effort("2-4", "Front knee tracks over the toes."),
          restSeconds: 75,
          notes: "Unilateral strength. Step back. Do not bounce out of the bottom.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Cable or band woodchop",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Hips turn, spine stays quiet."),
          restSeconds: 60,
          notes: "Rotational strength. Hands finish late. No yank from the low back.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Cable or band Pallof press",
          sets: 3,
          reps: "10 / side",
          loadText: effort("2-4", "Resist the twist."),
          restSeconds: 45,
          notes: "Anti-rotation. Press out and hold the finish for a breath.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Front plank",
          sets: 3,
          reps: "40 sec",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Brace. Log the hold time, not pounds.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: a.tuesday,
      title: "Day 2 — Upper pull + core",
      focus: `Explosive pull, rows, and trunk · ${mesoBlockLabel("A")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Dumbbell high pull",
          sets: 4,
          reps: "5",
          loadText: effort("3-5", "Snap the elbows. Stay fast."),
          restSeconds: 60,
          notes: "Explosive pull. Hips help, then the elbows finish high. Not a slow upright row.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "One-arm row",
          sets: 4,
          reps: "6 / side",
          loadText: effort("0-2", "Elbow to the hip.", "~80% of a 5-rep max"),
          restSeconds: 90,
          notes: "Main pull. Support the free hand. Last reps slow and stay clean.",
        }),
        liftExercise({
          sortOrder: 3,
          name: "Chin-up, band-assist, or lat pulldown",
          sets: 4,
          reps: "5–8",
          loadText: effort("1-3", "Full hang, control the lower."),
          restSeconds: 90,
          notes: "No bar? Slow inverted row or a heavy pulldown. Stop when the chin stops clearing.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Straight-arm pulldown",
          sets: 3,
          reps: "10",
          loadText: effort("2-4", "Ribs down, lats start the pull."),
          restSeconds: 60,
          notes: "Accessory lat. Arms stay nearly straight. No lean-back.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Band pull-apart or face pull",
          sets: 3,
          reps: "15",
          loadText: effort("2-4", "Shoulder blades meet."),
          restSeconds: 45,
          notes: "Rear shoulder health for class. Pause at the squeeze.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Dumbbell pullover",
          sets: 3,
          reps: "10",
          loadText: effort("2-4", "Ribs stay down."),
          restSeconds: 60,
          notes: "Reach long, then pull the bell back over the chest. Stop if the low back peels up.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dead bug",
          sets: 3,
          reps: "8 / side",
          loadText: "Slow — no load",
          restSeconds: 45,
          notes: "Low back stays glued. Exhale as the limb extends.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Side plank",
          sets: 3,
          reps: "25 sec / side",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Hips stacked. Log the hold time.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: a.wednesday,
      title: "Day 3 — Upper push + rotational power",
      focus: `Press, lockout, and rotational power · ${mesoBlockLabel("A")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Plyo push-up",
          sets: 4,
          reps: "5",
          loadText: effort("3-5", "Hands leave the floor. Land soft."),
          restSeconds: 45,
          notes: "Explosive push. Elevate the hands if a full plyo is too much. Speed over slop.",
        }),
        daruProgramExercise("Med-ball chest pass", 2),
        liftExercise({
          sortOrder: 3,
          name: "Dumbbell bench press",
          sets: 4,
          reps: "6",
          loadText: effort("0-2", "Last rep is slow and clean.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Main press. Dumbbells on a bench. Do not bounce the bells off the chest.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Overhead press",
          sets: 4,
          reps: "5",
          loadText: effort("0-2", "Ribs down at lockout.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Dumbbells or a light bar. Landmine if overhead bothers you. No lean-back to finish.",
        }),
        daruProgramExercise("Floor press", 5),
        daruProgramExercise("Landmine press", 6),
        daruProgramExercise("Rotational med-ball throw", 7),
        liftExercise({
          sortOrder: 8,
          name: "Landmine rotation",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Hips lead, arms follow."),
          restSeconds: 60,
          notes: "Slower rotational strength after the throws. Tall stance. No lumbar twist.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: THU_STRENGTH_DAY_NUMBER,
      title: "Day 11 — Posterior chain + unilateral",
      focus: `Swings, single-leg hinge, and carries · ${mesoBlockLabel("A")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Kettlebell swing or hip hinge",
          sets: 5,
          reps: "8",
          loadText: effort("3-5", "Snap the hips. Do not squat the bell."),
          restSeconds: 60,
          notes: "Posterior power. Quality dies, the set ends.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "Single-leg RDL",
          sets: 4,
          reps: "6 / leg",
          loadText: effort("1-3", "Soft knee, long reach."),
          restSeconds: 75,
          notes: "Main unilateral hinge. Hips stay square.",
        }),
        liftExercise({
          sortOrder: 3,
          name: "Dumbbell step-up",
          sets: 3,
          reps: "6 / leg",
          loadText: effort("2-4", "Drive the top foot. No push off the floor foot."),
          restSeconds: 75,
          notes: "Functional step. Knee tracks over the toes.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Farmer carry",
          sets: 3,
          reps: "40 sec",
          loadText: effort("2-3", "Heavy enough that you could walk a little farther."),
          restSeconds: 90,
          notes: "Walk tall. Log seconds and lbs.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Broad jump",
          sets: 4,
          reps: "4",
          loadText: effort("3-5", "Stick the landing."),
          restSeconds: 45,
          notes: "Horizontal power. Reset the stance before the next jump.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Dumbbell hip thrust",
          sets: 3,
          reps: "8",
          loadText: effort("2-4", "Pause at the top. Ribs down."),
          restSeconds: 60,
          notes: "Glutes finish the lockout. Do not over-arch.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dumbbell lateral lunge",
          sets: 3,
          reps: "6 / side",
          loadText: effort("2-4", "Sit into the hip. Trail leg stays long."),
          restSeconds: 60,
          notes: "Frontal-plane strength for stance changes.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Side plank",
          sets: 3,
          reps: "25 sec / side",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Hips stacked. Log the hold time.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: FRIDAY_GPP_DAY_NUMBER,
      title: "Day 10 — Friday GPP",
      focus: `Sled, carry, swing, and a lateral finisher · ${mesoBlockLabel("A")}`,
      exercises: [
        ...FRIDAY_GPP_NAMES.map((name, index) => daruProgramExercise(name, index + 1)),
        liftExercise({
          sortOrder: FRIDAY_GPP_NAMES.length + 1,
          name: "Lateral bound or side step-over",
          sets: 3,
          reps: "6 / side",
          loadText: effort("3-5", "Cover ground. Stick the landing."),
          restSeconds: 45,
          notes: "Athletic finisher after the GPP menu. Bound or step-over if a bound is too much.",
        }),
        liftExercise({
          sortOrder: FRIDAY_GPP_NAMES.length + 2,
          name: "Cable or band Pallof press",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Resist the twist."),
          restSeconds: 45,
          notes: "Trunk finisher. Different job than Thursday's hinge and carry.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: b.monday,
      title: "Day 12 — Lower body strength",
      focus: `Pause squat, single-leg hinge, and a chop · ${mesoBlockLabel("B")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Squat jump or box step-up",
          sets: 4,
          reps: "5",
          loadText: effort("3-5", "Same jump, sharper landing than Block A."),
          restSeconds: 45,
          notes: "Explosive primer before the pause squat.",
        }),
        daruProgramExercise("Trap-bar deadlift", 2),
        liftExercise({
          sortOrder: 3,
          name: "Pause goblet squat",
          sets: 4,
          reps: "5",
          loadText: effort("0-2", "Three-second pause in the hole.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Main squat. Stand only when the pause is quiet.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Single-leg RDL",
          sets: 4,
          reps: "6 / leg",
          loadText: effort("1-3", "Hinge, do not twist."),
          restSeconds: 75,
          notes: "Block B hinge is one leg. The free leg reaches back.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Walking lunge",
          sets: 3,
          reps: "8 / leg",
          loadText: effort("2-4", "Long step. Knee tracks."),
          restSeconds: 75,
          notes: "Do not bounce. Different pattern than Block A's reverse lunge.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Cable or band woodchop",
          sets: 3,
          reps: "6 / side",
          loadText: effort("2-4", "Slower than Block A. Own the turn."),
          restSeconds: 60,
          notes: "Rotational strength. Hips first.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Lateral bound or side step-over",
          sets: 3,
          reps: "5 / side",
          loadText: effort("3-5", "Stick each landing."),
          restSeconds: 45,
          notes: "Frontal power after the strength work.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Front plank",
          sets: 3,
          reps: "45 sec",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Harder brace than Block A. Log the hold time.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: b.tuesday,
      title: "Day 13 — Upper pull + core",
      focus: `Chest-supported row and a heavier vertical pull · ${mesoBlockLabel("B")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Dumbbell high pull",
          sets: 4,
          reps: "4",
          loadText: effort("3-5", "Heavier bell than Block A, still fast."),
          restSeconds: 60,
          notes: "Explosive pull. Stop if it turns into a shrug.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "Chest-supported dumbbell row",
          sets: 4,
          reps: "6",
          loadText: effort("0-2", "Elbows to the ribs.", "~85% of a 5-rep max"),
          restSeconds: 90,
          notes: "Main pull. Chest on a bench so the low back cannot cheat.",
        }),
        liftExercise({
          sortOrder: 3,
          name: "Chin-up, band-assist, or lat pulldown",
          sets: 4,
          reps: "4–6",
          loadText: effort("0-2", "Fewer reps, more load than Block A."),
          restSeconds: 90,
          notes: "Full hang. Control the lower.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Straight-arm pulldown",
          sets: 3,
          reps: "8",
          loadText: effort("2-4", "Stricter range than Block A."),
          restSeconds: 60,
          notes: "Ribs down.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Band pull-apart or face pull",
          sets: 3,
          reps: "15",
          loadText: effort("2-4", "One-second squeeze."),
          restSeconds: 45,
          notes: "Shoulder blades meet.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Dumbbell pullover",
          sets: 3,
          reps: "8",
          loadText: effort("2-4", "Heavier than Block A."),
          restSeconds: 60,
          notes: "Ribs stay down.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dead bug",
          sets: 3,
          reps: "10 / side",
          loadText: "Slow — no load",
          restSeconds: 45,
          notes: "Slower than Block A. Low back stays down.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Side plank",
          sets: 3,
          reps: "30 sec / side",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Hips stacked. Log the hold.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: b.wednesday,
      title: "Day 14 — Upper push + rotational power",
      focus: `Heavy five and single-arm lockout · ${mesoBlockLabel("B")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Plyo push-up",
          sets: 4,
          reps: "4",
          loadText: effort("3-5", "Fewer reps, higher intent."),
          restSeconds: 45,
          notes: "Explosive push before the heavy five.",
        }),
        daruProgramExercise("Med-ball chest pass", 2),
        liftExercise({
          sortOrder: 3,
          name: "Dumbbell bench press",
          sets: 5,
          reps: "5",
          loadText: effort("0-2", "Last rep is slow and clean.", "~85% of a 5-rep max"),
          restSeconds: 120,
          notes: "Block B press is fewer reps and more load than Block A.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Single-arm overhead press",
          sets: 4,
          reps: "5 / side",
          loadText: effort("1-3", "Strict. No lean."),
          restSeconds: 90,
          notes: "One dumbbell. Ribs down. The free hand can touch the ribs, not the thigh.",
        }),
        daruProgramExercise("Floor press", 5),
        daruProgramExercise("Landmine press", 6),
        daruProgramExercise("Rotational med-ball throw", 7),
        liftExercise({
          sortOrder: 8,
          name: "Landmine rotation",
          sets: 3,
          reps: "6 / side",
          loadText: effort("2-4", "Heavier bar than Block A."),
          restSeconds: 60,
          notes: "Rotational strength after the throws.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: b.thursday,
      title: "Day 15 — Posterior chain + unilateral",
      focus: `Heavier swing, bilateral hinge, and a suitcase · ${mesoBlockLabel("B")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Kettlebell swing or hip hinge",
          sets: 5,
          reps: "8",
          loadText: effort("3-5", "Heavier bell. Still crisp."),
          restSeconds: 60,
          notes: "Power hinge. Stop if the bell turns into a squat.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "Dumbbell Romanian deadlift",
          sets: 4,
          reps: "6",
          loadText: effort("0-2", "Flat back.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Two dumbbells. Different tool than Monday's trap bar.",
        }),
        liftExercise({
          sortOrder: 3,
          name: "Dumbbell step-up",
          sets: 3,
          reps: "6 / leg",
          loadText: effort("2-4", "Taller step than Block A if the knee stays quiet."),
          restSeconds: 75,
          notes: "Drive the top foot.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Suitcase carry",
          sets: 3,
          reps: "40 sec / side",
          loadText: effort("2-3", "One side heavy. Stay tall."),
          restSeconds: 75,
          notes: "Anti-lean carry. Log seconds and lbs.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Broad jump",
          sets: 4,
          reps: "3",
          loadText: effort("3-5", "Max distance you can stick."),
          restSeconds: 60,
          notes: "Reset fully between jumps.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Dumbbell hip thrust",
          sets: 3,
          reps: "6",
          loadText: effort("1-3", "Heavier than Block A. Pause on top."),
          restSeconds: 75,
          notes: "Ribs down.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dumbbell lateral lunge",
          sets: 3,
          reps: "6 / side",
          loadText: effort("2-4", "Deeper hip than Block A."),
          restSeconds: 60,
          notes: "Trail leg stays long.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Side plank",
          sets: 3,
          reps: "30 sec / side",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Hips stacked. Log the hold.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: b.friday,
      title: "Day 16 — Friday GPP",
      focus: `GPP, repeat efforts, and a trunk finisher · ${mesoBlockLabel("B")}`,
      exercises: [
        ...FRIDAY_GPP_NAMES.map((name, index) => daruProgramExercise(name, index + 1)),
        liftExercise({
          sortOrder: FRIDAY_GPP_NAMES.length + 1,
          name: "Burpees",
          sets: 4,
          reps: "30 sec",
          loadText: effort("3-5", "Hard and repeatable. No lbs."),
          restSeconds: 45,
          notes: "Stand-up burpee. Stop if the hips pike and the set turns sloppy.",
        }),
        liftExercise({
          sortOrder: FRIDAY_GPP_NAMES.length + 2,
          name: "Cable or band Pallof press",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Resist the twist."),
          restSeconds: 45,
          notes: "Trunk finisher after the repeats.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: c.monday,
      title: "Day 17 — Lower body strength",
      focus: `Lunge-led lower day and a Pallof · ${mesoBlockLabel("C")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Squat jump or box step-up",
          sets: 3,
          reps: "5",
          loadText: effort("3-5", "Shorter primer. Save the legs for the lunge."),
          restSeconds: 45,
          notes: "Explosive opener.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "Walking lunge",
          sets: 4,
          reps: "6 / leg",
          loadText: effort("0-2", "This is the main lift.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Long step. Last reps on each leg should slow and stay clean.",
        }),
        daruProgramExercise("Trap-bar deadlift", 3),
        liftExercise({
          sortOrder: 4,
          name: "Single-leg RDL",
          sets: 4,
          reps: "5 / leg",
          loadText: effort("1-3", "Fewer reps than Block B. Own the balance."),
          restSeconds: 75,
          notes: "Hinge, do not twist.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Goblet squat",
          sets: 3,
          reps: "6",
          loadText: effort("1-3", "Two seconds down."),
          restSeconds: 90,
          notes: "Squat stays in the day as a secondary lift, not the Block A grind.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Cable or band Pallof press",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Longer hold at the finish than Block A."),
          restSeconds: 45,
          notes: "Anti-rotation between the lower work and the lateral lunge.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dumbbell lateral lunge",
          sets: 3,
          reps: "6 / side",
          loadText: effort("2-4", "Sit into the hip."),
          restSeconds: 60,
          notes: "Frontal-plane strength.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Side plank",
          sets: 3,
          reps: "30 sec / side",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Hips stacked. Log the hold.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: c.tuesday,
      title: "Day 18 — Upper pull + core",
      focus: `Half-kneeling row, pullover, and a shrug · ${mesoBlockLabel("C")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Dumbbell high pull",
          sets: 3,
          reps: "5",
          loadText: effort("3-5", "Fast elbows."),
          restSeconds: 60,
          notes: "Explosive pull before the strict row.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "Half-kneeling one-arm row",
          sets: 4,
          reps: "6 / side",
          loadText: effort("0-2", "Torso quiet.", "~80% of a 5-rep max"),
          restSeconds: 90,
          notes: "Half-kneeling so the low back cannot cheat. Elbow to the hip.",
        }),
        liftExercise({
          sortOrder: 3,
          name: "Chin-up, band-assist, or lat pulldown",
          sets: 4,
          reps: "6–8",
          loadText: effort("1-3", "Strict range, not a heavier triple."),
          restSeconds: 90,
          notes: "Full hang. Smooth lower.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Straight-arm pulldown",
          sets: 3,
          reps: "10",
          loadText: effort("2-4", "Full stretch, ribs down."),
          restSeconds: 60,
          notes: "Lat accessory.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Band pull-apart or face pull",
          sets: 4,
          reps: "12",
          loadText: effort("2-4", "Extra set versus Block A."),
          restSeconds: 45,
          notes: "Shoulder blades still meet.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Dumbbell pullover",
          sets: 3,
          reps: "10",
          loadText: effort("2-4", "Long reach."),
          restSeconds: 60,
          notes: "Ribs stay down.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dead bug",
          sets: 3,
          reps: "8 / side",
          loadText: "Slow — no load",
          restSeconds: 45,
          notes: "Low back stays glued.",
        }),
        daruProgramExercise("Bent-over DB shrug", 8),
      ],
    }),
    strengthDay({
      dayNumber: c.wednesday,
      title: "Day 19 — Upper push + rotational power",
      focus: `Paused press and strict overhead · ${mesoBlockLabel("C")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Plyo push-up",
          sets: 3,
          reps: "5",
          loadText: effort("3-5", "Speed first."),
          restSeconds: 45,
          notes: "Explosive opener before the pause.",
        }),
        daruProgramExercise("Med-ball chest pass", 2),
        liftExercise({
          sortOrder: 3,
          name: "Dumbbell bench press",
          sets: 4,
          reps: "6",
          loadText: effort("0-2", "One-second pause on the chest.", "~80% of a 5-rep max"),
          restSeconds: 120,
          notes: "Block C is a pause, not Block B's heavy five.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Overhead press",
          sets: 4,
          reps: "5",
          loadText: effort("0-2", "Stricter than Block A.", "~85% of a 5-rep max"),
          restSeconds: 120,
          notes: "No leg drive. Stop if the ribs flare to finish the lockout.",
        }),
        daruProgramExercise("Floor press", 5),
        daruProgramExercise("Landmine press", 6),
        daruProgramExercise("Rotational med-ball throw", 7),
        liftExercise({
          sortOrder: 8,
          name: "Landmine rotation",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Smooth turn, heavy enough to feel."),
          restSeconds: 60,
          notes: "Rotational strength after the power throws.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: c.thursday,
      title: "Day 20 — Posterior chain + unilateral",
      focus: `Longer swings, a step-up, and two carries · ${mesoBlockLabel("C")}`,
      exercises: [
        liftExercise({
          sortOrder: 1,
          name: "Kettlebell swing or hip hinge",
          sets: 4,
          reps: "12",
          loadText: effort("3-5", "More reps than Block B. Hips still snap."),
          restSeconds: 60,
          notes: "Quality dies, the set ends.",
        }),
        liftExercise({
          sortOrder: 2,
          name: "Single-leg RDL",
          sets: 3,
          reps: "8 / leg",
          loadText: effort("2-4", "Higher reps than Block B. Balance first."),
          restSeconds: 75,
          notes: "Square hips.",
        }),
        liftExercise({
          sortOrder: 3,
          name: "Dumbbell step-up",
          sets: 3,
          reps: "8 / leg",
          loadText: effort("2-4", "Controlled down."),
          restSeconds: 75,
          notes: "Drive the top foot.",
        }),
        liftExercise({
          sortOrder: 4,
          name: "Suitcase carry",
          sets: 4,
          reps: "30 sec / side",
          loadText: effort("2-3", "One more set than Block B."),
          restSeconds: 60,
          notes: "Do not lean. Log seconds and lbs.",
        }),
        liftExercise({
          sortOrder: 5,
          name: "Farmer carry",
          sets: 3,
          reps: "40 sec",
          loadText: effort("2-3", "Both hands. Walk tall."),
          restSeconds: 75,
          notes: "Bilateral carry after the suitcase. Log seconds and lbs.",
        }),
        liftExercise({
          sortOrder: 6,
          name: "Broad jump",
          sets: 3,
          reps: "4",
          loadText: effort("3-5", "Stick the landing."),
          restSeconds: 45,
          notes: "Horizontal power while the hips are warm.",
        }),
        liftExercise({
          sortOrder: 7,
          name: "Dumbbell hip thrust",
          sets: 3,
          reps: "10",
          loadText: effort("2-4", "Higher reps than Block B."),
          restSeconds: 60,
          notes: "Pause on top. Ribs down.",
        }),
        liftExercise({
          sortOrder: 8,
          name: "Side plank",
          sets: 3,
          reps: "30 sec / side",
          loadText: "Hold — no weight",
          restSeconds: 45,
          notes: "Hips stacked. Log the hold.",
        }),
      ],
    }),
    strengthDay({
      dayNumber: c.friday,
      title: "Day 21 — Friday GPP",
      focus: `GPP, jump rope, and a trunk finisher · ${mesoBlockLabel("C")}`,
      exercises: [
        ...FRIDAY_GPP_NAMES.map((name, index) => daruProgramExercise(name, index + 1)),
        liftExercise({
          sortOrder: FRIDAY_GPP_NAMES.length + 1,
          name: "Jump rope or easy bike intervals",
          sets: 6,
          reps: "30 sec on / 30 sec easy",
          loadText: "Smooth — no lbs",
          restSeconds: 0,
          notes: "After the GPP menu. Stay tall on the rope or easy on the bike. This is the Block C finisher, not a second sled.",
        }),
        liftExercise({
          sortOrder: FRIDAY_GPP_NAMES.length + 2,
          name: "Cable or band Pallof press",
          sets: 3,
          reps: "8 / side",
          loadText: effort("2-4", "Resist the twist."),
          restSeconds: 45,
          notes: "Trunk finisher. Quiet ribs.",
        }),
      ],
    }),
  ];
}

function bagSkillDay(block: MesoBlock, weekday: BagWeekday) {
  const plan = bagFocusFor(weekday, block);
  const technique = plan.technique;
  const exercises = [
    ...shadowRounds(plan.shadowEmpty, plan.shadowWeighted),
    ...(technique
      ? [
          {
            sortOrder: 3,
            name: technique.name,
            sets: 3,
            reps: technique.reps,
            loadText: technique.loadText,
            restSeconds: 45,
            notes: `${technique.notes} ${BAG_OR_SHADOW}`,
            ...formVideoFieldsFor(technique.name),
          },
        ]
      : []),
    bagRoundBlock({
      sortOrder: technique ? 4 : 3,
      name: plan.bagName,
      notes: formatBagRoundNotes(plan.rounds),
    }),
    {
      sortOrder: technique ? 5 : 4,
      name: SHADOW_COOL_NAME,
      sets: 1,
      reps: "2:00",
      loadText: "Breathe — no power",
      restSeconds: 0,
      notes:
        weekday === "Saturday"
          ? "Walk it down. Optional Saturday — skip if you need the rest."
          : "Hands up, loose shoulders. Soft technical shadow — no power.",
      ...formVideoFieldsFor(SHADOW_COOL_NAME),
    },
  ];
  return {
    dayNumber: plan.dayNumber,
    title: plan.label,
    focus: `${plan.theme} · ${mesoBlockLabel(block)}`,
    exercises: { create: exercises },
  };
}

/** Bag / combat skill catalog days for demo-combat-skills. Three blocks, same weekdays. */
export function demoBagSkillDays() {
  return MESO_BLOCKS.flatMap((block) => BAG_WEEKDAYS.map((weekday) => bagSkillDay(block, weekday)));
}
