import { randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const envPath = path.resolve(process.cwd(), ".env");
if (fs.existsSync(envPath)) {
  console.log(".env already exists — leaving it alone.");
  process.exit(0);
}

const secret = randomBytes(32).toString("hex");
const contents = `DATABASE_URL="file:./dev.db"
AUTH_SECRET="${secret}"
APP_URL="http://localhost:3000"
SMTP_HOST=
SMTP_PORT=
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
ADMIN_BOOTSTRAP_EMAIL=
OPENAI_API_KEY=
OPENAI_MODEL=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_GYM=
STRIPE_PRICE_STANDALONE=
STRIPE_PRICE_PERFORMANCE_ANNUAL_GYM=
STRIPE_PRICE_PERFORMANCE_ANNUAL_NON=
STRIPE_PRICE_PERFORMANCE_FOUNDING_GYM=
STRIPE_PRICE_PERFORMANCE_FOUNDING_NON=
STRIPE_PRICE_CONDITIONING_GYM=
STRIPE_PRICE_CONDITIONING_NON=
STRIPE_PRICE_CONDITIONING_CAMP_GYM=
STRIPE_PRICE_CONDITIONING_CAMP_NON=
STRIPE_PRICE_CONDITIONING_ANNUAL_GYM=
STRIPE_PRICE_CONDITIONING_ANNUAL_NON=
STRIPE_PRICE_CONDITIONING_FOUNDING_GYM=
STRIPE_PRICE_CONDITIONING_FOUNDING_NON=
STRIPE_PRICE_DEVELOPMENT_GYM=
STRIPE_PRICE_DEVELOPMENT_NON=
STRIPE_PRICE_DEVELOPMENT_3MO_GYM=
STRIPE_PRICE_DEVELOPMENT_3MO_NON=
STRIPE_PRICE_DEVELOPMENT_6MO_GYM=
STRIPE_PRICE_DEVELOPMENT_6MO_NON=
STRIPE_PRICE_ELITE_GYM=
STRIPE_PRICE_ELITE_NON=
STRIPE_PRICE_ELITE_3MO_GYM=
STRIPE_PRICE_ELITE_3MO_NON=
STRIPE_PRICE_ELITE_6MO_GYM=
STRIPE_PRICE_ELITE_6MO_NON=
STRIPE_PRICE_VIP=
STRIPE_PRICE_PLATINUM=
PROGRESS_PHOTO_DIR=
POLAR_CLIENT_ID=
POLAR_CLIENT_SECRET=
POLAR_REDIRECT_URI=
GYMDESK_WEBHOOK_SECRET=
GYMDESK_MATCH_PEPPER=
GYMDESK_SYNC_ENABLED=
GYMDESK_GRACE_DAYS=7
GYMDESK_FROZEN_GRACE_DAYS=30
GYMDESK_STALE_DAYS=35
CRON_SECRET=
`;

fs.writeFileSync(envPath, contents);
console.log("Created .env for local preview (SQLite).");
